# Generated by Django 5.1.1 on 2024-11-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_chapters_alter_book_favorites_chapters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chapters',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='favorites_chapters',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
