# Generated by Django 5.2 on 2025-04-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_recentlyviewedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentimentCategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='textSentimentScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
